version: "3.9"

services:
  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - /home/skynet/Downloads/github-repos/siemids/certs:/usr/share/elasticsearch/config/certs
    user: "0"
    secrets:
      - elastic_password
      - kibana_password
    command: >
      bash -c '
        ELASTIC_PASSWORD=$(cat /run/secrets/elastic_password)
        KIBANA_PASSWORD=$(cat /run/secrets/kibana_password)
        if [ x${ELASTIC_PASSWORD} == x ]; then
          echo "Set the ELASTIC_PASSWORD secret";
          exit 1;
        elif [ x${KIBANA_PASSWORD} == x ]; then
          echo "Set the KIBANA_PASSWORD secret";
          exit 1;
        fi;
        if [ ! -f config/certs/ca.zip ]; then
          echo "Creating CA";
          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
          unzip config/certs/ca.zip -d config/certs;
        fi;
        if [ ! -f config/certs/certs.zip ]; then
          echo "Creating certs";
          echo -ne \
          "instances:\n"\
          "  - name: es01\n"\
          "    dns:\n"\
          "      - es01\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: kibana\n"\
          "    dns:\n"\
          "      - kibana\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: filebeat\n"\
          "    dns:\n"\
          "      - filebeat\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: logstash\n"\
          "    dns:\n"\
          "      - logstash\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          > config/certs/instances.yml;
          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
          unzip config/certs/certs.zip -d config/certs;
        fi;
        until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" https://es01:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
        echo "All done!";
      '
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/es01/es01.crt ]"]
      interval: 1s
      timeout: 5s
      retries: 120
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m

  es01:
    restart: always
    depends_on:
      setup:
        condition: service_healthy
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - /home/skynet/Downloads/github-repos/siemids/certs:/usr/share/elasticsearch/config/certs
      - es01data:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    deploy:
      resources:
        limits:
          memory: 8g
        reservations:
          memory: 6g
    environment:
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es01
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enrollment.enabled=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es01/es01.key
      - xpack.security.http.ssl.certificate=certs/es01/es01.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es01/es01.key
      - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://es01:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    restart: always
    depends_on:
      es01:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    volumes:
      - /home/skynet/Downloads/github-repos/siemids/certs:/usr/share/kibana/config/certs
      - kibanadata:/usr/share/kibana/data
      - /home/skynet/Downloads/github-repos/siemids/resources/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - /var/run/secrets:/run/secrets
    ports:
      - ${KIBANA_PORT}:5601
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 2g
    environment:
      - NODE_OPTIONS=--max-old-space-size=2048
      - SERVERNAME=kibana
      - XPACK_SECURITY_ENABLED=true
      - ELASTICSEARCH_HOSTS=https://es01:9200
      - ELASTICSEARCH_URL=https://es01:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=certificate
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_KEY=config/certs/kibana/kibana.key
      - SERVER_SSL_CERTIFICATE=config/certs/kibana/kibana.crt
      - xpack.encryptedSavedObjects.encryptionKey="9XeNMpw3EYfxst2XhHE5gj3GRr22k9y59KkYX6DD"
      - xpack.reporting.capture.browser.chromium.disableSandbox=true
      - server.publicBaseUrl=https://siemids:5601
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I --cacert config/certs/ca/ca.crt https://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  setup_kibana:
    restart: on-failure
    depends_on:
      kibana:
        condition: service_healthy
    image: docker.io/alpine/curl
    network_mode: host
    volumes: 
      - /home/skynet/Downloads/github-repos/siemids/certs:/usr/local/certs
      - /home/skynet/Downloads/github-repos/siemids/saved.objects:/usr/local/saved.objects
    command: >
      sh -c '
        until curl -s -I --cacert /usr/local/certs/ca/ca.crt https://localhost:5601 | grep -q "HTTP/1.1 302 Found"; do
          echo "Waiting for Kibana to be ready...";
          sleep 10;
        done;
        curl -s -X POST "https://localhost:5601/api/saved_objects/_import?compatibilityMode=true" -H "kbn-xsrf: true" --cacert /usr/local/certs/ca/ca.crt --cert /usr/local/certs/es01/es01.crt --key /usr/local/certs/es01/es01.key -u elastic:${ELASTIC_PASSWORD} --form file=@/usr/local/saved.objects/siemids.ndjson
      '
    environment: 
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 128m

  filebeat:
    restart: unless-stopped
    depends_on:
      es01:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 256m
    image: docker.elastic.co/beats/filebeat:${STACK_VERSION}
    command: ["filebeat", "--environment", "container", "-c", "/usr/share/filebeat/filebeat.yml"]
    user: root
#  network_mode: host
    volumes:
      - /home/skynet/Downloads/github-repos/siemids/resources/filebeat/filebeat-siemids.yml:/usr/share/filebeat/filebeat.yml
      - /home/skynet/Downloads/github-repos/siemids/resources/suricata/suricata.yml:/usr/share/filebeat/modules.d/suricata.yml
      - /home/skynet/Downloads/github-repos/siemids/env/localnet.env:/usr/share/filebeat/localnet.env
      - /home/skynet/Downloads/github-repos/siemids/env/pianet.env:/usr/share/filebeat/pianet.env
      - /home/skynet/Downloads/github-repos/siemids/certs:/usr/share/elasticsearch/config/certs
      # /var/run/podman/podman.sock:/var/run/podman/podman.sock
      # /var/lib/containers/:/var/lib/containers/:ro
      # This is needed for filebeat to load logs for system and auth modules
      - /var/log/:/var/log/:ro
      - /suricata/:/suricata/:ro
    env_file:
      - /home/skynet/Downloads/github-repos/siemids/env/localnet.env
      - /home/skynet/Downloads/github-repos/siemids/env/pianet.env
    environment:
      - ELASTICSEARCH_HOSTS=https://localhost:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt

  # alienvault-flask_api:
  #   restart: always
  #   depends_on:
  #     kibana:
  #       condition: service_healthy
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: alienvault-flask_api
  #   network_mode: bridge
  #   ports:
  #     - "5000:5000"

  #  metricbeat:
  #    image: docker.elastic.co/beats/metricbeat:${STACK_VERSION}
  #    user: root
  #    volumes:
  #      - /home/skynet/Downloads/github-repos/siemids/resources/metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
  #      - /home/skynet/Downloads/github-repos/siemids/certs:/usr/share/metricbeat/config/certs/
  #      - /proc:/hostfs/proc:ro
  #      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
  #      - /:/hostfs:ro
  #    environment:
  #      - ELASTICSEARCH_HOSTS=https://es01:9200
  #      - ELASTICSEARCH_USERNAME=elastic
  #      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
  #      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=/usr/share/metricbeat/config/certs/ca/ca.crt
  #      - system.hostfs=/hostfs
  #    command: ["metricbeat", "-e", "-c", "/usr/share/metricbeat/metricbeat.yml"]
secrets:
  elastic_password:
    external: true
  kibana_password:
    external: true

volumes:
  es01data:
    driver: local
  kibanadata:
    driver: local
