hostname: "raspberrysrv"
agent.hostname: "raspberrysrv"
name: "raspberrysrv"
tags: ["raspberrysrv", "suricata", "dns"]

#============================= Filebeat modules ===============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: true

  # Period on which files under path should be checked for changes
  reload.period: 120s

filebeat.modules:
- module: auditd
  log:
    enabled: true
    var.paths: ["/nas/var/log/audit/audit.log*"]
- module: system
  syslog:
    enabled: true
    var.paths: ["/nas/var/log/syslog*"]
  auth:
    enabled: true
    var.paths: ["/nas/var/log/auth.log*"]

# ======================= Elasticsearch template setting =======================

#setup.template.enabled: true
#setup.template.name: "filebeat-%{[agent.version]}"
#setup.template.pattern: "filebeat-%{[agent.version]}-*"

setup.template.settings:
  index.number_of_shards: 3
  index.number_of_replicas: 1
  #index.codec: best_compression
  #_source.enabled: false

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

processors:
  - add_fields:
      when:
        or:
          - contains:
              source.ip: "10.1.1."
          - contains:
              source.ip: "10.10.10."
          - contains:
              source.ip: "192.168.100."
      target: 'source.geo'
      fields:
        location: POINT (-58.5085 -34.5131)
        country_name: Argentina
        country_iso_code: AR
        region_iso_code: AR-C
        continent_name: South America
        region_name: Buenos Aires
        city_name: Olivos

  - add_fields:
      when:
        or:
          - contains:
              source.ip: "10.1.1."
          - contains:
              source.ip: "10.10.10."
          - contains:
              source.ip: "192.168.100."
      target: 'source.as'
      fields:
        organization.name: Local Networks 

  - add_fields:
      when:
        or:
          - contains:
              source.ip: "10.24.19.26"
      target: 'source.geo'
      fields:
        location: POINT (-3.7037 40.4167)
        country_name: España
        country_iso_code: ES
        region_iso_code: ES-M
        continent_name: Europe
        region_name: Madrid
        city_name: Madrid

  - add_fields:
      when:
        or:
          - contains:
              source.ip: "10.24.19.26"
      target: 'source.as'
      fields:
        organization.name: OpenVPN PIA

  - add_fields:
      when:
        or:
          - contains:
              source.ip: "10.10.231.98"
      target: 'source.geo'
      fields:
        location: POINT (14.4719 35.9183)
        country_name: Malta
        country_iso_code: MT
        region_iso_code: MT
        continent_name: Europe
        region_name: Is-Swieqi
        city_name: Il-Madliena

  - add_fields:
      when:
        or:
          - contains:
              source.ip: "10.10.231.98"
      target: 'source.as'
      fields:
        organization.name: WireGuard PIA

  - add_fields:
      when:
        or:
          - contains:
              destination.ip: "10.1.1."
          - contains:
              destination.ip: "10.10.10."
          - contains:
              destination.ip: "192.168.100."
      target: 'destination.geo'
      fields:
        location: POINT (-58.5085 -34.5131)
        country_name: Argentina
        country_iso_code: AR
        region_iso_code: AR-C
        continent_name: South America
        region_name: Buenos Aires
        city_name: Olivos

  - add_fields:
      when:
        or:
          - contains:
              destination.ip: "10.1.1."
          - contains:
              destination.ip: "10.10.10."
          - contains:
              destination.ip: "192.168.100."
      target: 'destination.as'
      fields:
        organization.name: Local Networks 

  - add_fields:
      when:
        or:
          - contains:
              destination.ip: "10.24.19.26"
      target: 'destination.geo'
      fields:
        location: POINT (-3.7037 40.4167)
        country_name: España
        country_iso_code: ES
        region_iso_code: ES-M
        continent_name: Europe
        region_name: Madrid
        city_name: Madrid

  - add_fields:
      when:
        or:
          - contains:
              destination.ip: "10.24.19.26"
      target: 'destination.as'
      fields:
        organization.name: OpenVPN PIA

  - add_fields:
      when:
        or:
          - contains:
              destination.ip: "10.10.231.98"
      target: 'destination.geo'
      fields:
        location: POINT (14.4719 35.9183)
        country_name: Malta
        country_iso_code: MT
        region_iso_code: MT
        continent_name: Europe
        region_name: Is-Swieqi
        city_name: Il-Madliena

  - add_fields:
      when:
        or:
          - contains:
              destination.ip: "10.10.231.98"
      target: 'destination.as'
      fields:
        organization.name: WireGuard PIA

  - add_fields:
      when:
        or:
          - contains:
              destination.ip: "10.0.0.241"
      target: 'destination.geo'
      fields:
        location: POINT (-3.7037 40.4167)
        country_name: España
        country_iso_code: ES
        region_iso_code: ES-M
        continent_name: Europe
        region_name: Madrid
        city_name: Madrid

  - add_fields:
      when:
        or:
          - contains:
              destination.ip: "10.0.0.241"
      target: 'destination.as'
      fields:
        organization.name: PIA - DNS

output.elasticsearch:
  hosts: ["https://localhost:9200"]
#  index: "logs-%{+yyyy.MM.dd}"
#  indices:
#    - index: "suricata-logs-%{+yyyy.MM.dd}"
#      when.equals:
#        event.module: "suricata"
#    - index: "audit-logs-%{+yyyy.MM.dd}"
#      when.equals:
#        event.module: "auditd"
#    - index: "system-logs-%{+yyyy.MM.dd}"
#      when.equals:
#        event.module: "system"
  username: elastic
  password: Sys04531
  ssl:
    certificate_authorities: "/usr/share/elasticsearch/config/certs/ca/ca.crt"
    certificate: "/usr/share/elasticsearch/config/certs/filebeat/filebeat.crt"
    key: "/usr/share/elasticsearch/config/certs/filebeat/filebeat.key"

