hostname: "ryzen9"
agent.hostname: "ryzen9"
name: "ryzen9"
tags: ["ryzen9", "suricata", "dns"]

filebeat.config.inputs:
  enabled: true
  reload.enabled: true
  reload.period: 10s
  env:
    - localnet.env
    - pianet.env

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/pihole/pihole.log
      - /var/log/pihole/pihole-FTL.log
    fields:
      event.dataset: pihole.log
    fields_under_root: true

#============================= Filebeat modules ===============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: true

  # Period on which files under path should be checked for changes
  reload.period: 120s

filebeat.modules:
- module: auditd
  log:
    enabled: true
    var.paths: ["/var/log/audit/audit.log*"]
- module: system
  syslog:
    enabled: true
    var.paths: ["/var/log/syslog*"]
  auth:
    enabled: true
    var.paths: ["/var/log/auth.log*"]

# ======================= Elasticsearch template setting =======================

#setup.template.enabled: true
#setup.template.name: "filebeat-%{[agent.version]}"
#setup.template.pattern: "filebeat-%{[agent.version]}-*"

setup.template.settings:
  index.number_of_shards: 3
  index.number_of_replicas: 1
  #index.codec: best_compression
  #_source.enabled: false

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

###
### Local Networks
###

  - add_fields:
      when:
        or:
          - contains:
              source.ip: "10.1.1."
          - contains:
              source.ip: "10.10.10."
          - contains:
              source.ip: "192.168.1."
      target: 'source.geo'
      fields:
        location: POINT (${localnet_geo_LON} ${localnet_geo_LAT})
        country_name: '${localnet_geo_COUNTRY}'
        country_iso_code: '${localnet_geo_COUNTRYCODE}'
        region_iso_code: '${localnet_geo_REGION}'
        continent_name: '${localnet_geo_TIMEZONE}'
        region_name: '${localnet_geo_REGIONNAME}'
        city_name: '${localnet_geo_CITY}'

  - add_fields:
      when:
        or:
          - contains:
              source.ip: "10.1.1."
          - contains:
              source.ip: "10.10.10."
          - contains:
              source.ip: "192.168.1."
      target: 'source.as'
      fields:
        organization.name: '${localnet_geo_ORG}'

  - add_fields:
      when:
        or:
          - contains:
              destination.ip: "10.1.1."
          - contains:
              destination.ip: "10.10.10."
          - contains:
              destination.ip: "192.168.1."
      target: 'destination.geo'
      fields:
        location: POINT (${localnet_geo_LON} ${localnet_geo_LAT})
        country_name: '${localnet_geo_COUNTRY}'
        country_iso_code: '${localnet_geo_COUNTRYCODE}'
        region_iso_code: '${localnet_geo_REGION}'
        continent_name: '${localnet_geo_TIMEZONE}'
        region_name: '${localnet_geo_REGIONNAME}'
        city_name: '${localnet_geo_CITY}'

  - add_fields:
      when:
        or:
          - contains:
              destination.ip: "10.1.1."
          - contains:
              destination.ip: "10.10.10."
          - contains:
              host.mac: "192.168.1."
      target: 'destination.as'
      fields:
        organization.name: '${localnet_geo_ORG}'

###
### WireGuard
###

  - add_fields:
      when:
        or:
          - contains:
              source.ip: '${pianet_iface_WG0}'
      target: 'source.geo'
      fields:
        location: POINT (${pianet_geo_LON} ${pianet_geo_LAT})
        country_name: '${pianet_geo_COUNTRY}'
        country_iso_code: '${pianet_geo_COUNTRYCODE}'
        region_iso_code: '${pianet_geo_REGION}'
        continent_name: '${pianet_geo_TIMEZONE}'
        region_name: '${pianet_geo_REGIONNAME}'
        city_name: '${pianet_geo_CITY}'

  - add_fields:
      when:
        or:
          - contains:
              source.ip: '${pianet_iface_WG0}'
      target: 'source.as'
      fields:
        organization.name: '${pianet_geo_ORG}'

  - add_fields:
      when:
        or:
          - contains:
              destination.ip: '${pianet_iface_WG0}'
      target: 'destination.geo'
      fields:
        location: POINT (${pianet_geo_LON} ${pianet_geo_LAT})
        country_name: '${pianet_geo_COUNTRY}'
        country_iso_code: '${pianet_geo_COUNTRYCODE}'
        region_iso_code: '${pianet_geo_REGION}'
        continent_name: '${pianet_geo_TIMEZONE}'
        region_name: '${pianet_geo_REGIONNAME}'
        city_name: '${pianet_geo_CITY}'

  - add_fields:
      when:
        or:
          - contains:
              destination.ip: '${pianet_iface_WG0}'
      target: 'destination.as'
      fields:
        organization.name: '${pianet_geo_ORG}'

###
### DNS PIA UPSTREAM
###

  - add_fields:
      when:
        or:
          - contains:
              destination.ip: "10.0.0.241"
      target: 'destination.geo'
      fields:
        location: POINT (${pianet_geo_LON} ${pianet_geo_LAT})
        country_name: '${pianet_geo_COUNTRY}'
        country_iso_code: '${pianet_geo_COUNTRYCODE}'
        region_iso_code: '${pianet_geo_REGION}'
        continent_name: '${pianet_geo_TIMEZONE}'
        region_name: '${pianet_geo_REGIONNAME}'
        city_name: '${pianet_geo_CITY}'

  - add_fields:
      when:
        or:
          - contains:
              destination.ip: "10.0.0.241"
      target: 'destination.as'
      fields:
        organization.name: '${pianet_geo_ORG}'

  # Parse the main structure of the pihole log
  - dissect:
      tokenizer: "%{timestamp} %{+timestamp} %{+timestamp} %{service}[%{pid}]: %{message}"
      field: "message"
      target_prefix: ""

  - dissect:
      when:
        contains:
          message: "query"
      tokenizer: "%{timestamp} %{+timestamp} %{+timestamp} %{service}[%{pid}]: %{action}[%{type}] %{domain} from %{source_ip}"
      field: "message"
      target_prefix: "query"
  - rename:
      when:
        has_fields: ["query.action"]
      fields:
        - from: "query.action"
          to: "event.action"
  - rename:
      when:
        has_fields: ["query.domain"]
      fields:
        - from: "query.domain"
          to: "event.domain"
  - rename:
      when:
        has_fields: ["query.source_ip"]
      fields:
        - from: "query.source_ip"
          to: "source.ip"

  - dissect:
      when:
        contains:
          message: "reply"
      tokenizer: "%{timestamp} %{+timestamp} %{+timestamp} %{service}[%{pid}]: %{action} %{domain} is %{data}"
      field: "message"
      target_prefix: "reply"
  - rename:
      when:
        has_fields: ["reply.action"]
      fields:
        - from: "reply.action"
          to: "event.action"
  - rename:
      when:
        has_fields: ["reply.domain"]
      fields:
        - from: "reply.domain"
          to: "event.domain"
  - rename:
      when:
        has_fields: ["reply.data"]
      fields:
        - from: "reply.data"
          to: "destination.ip"

  - dissect:
      when:
        contains:
          message: "forwarded"
      tokenizer: "%{timestamp} %{+timestamp} %{+timestamp} %{service}[%{pid}]: %{action} %{domain} to %{data}"
      field: "message"
      target_prefix: "forwarded"
  - rename:
      when:
        has_fields: ["forwarded.action"]
      fields:
        - from: "forwarded.action"
          to: "event.action"
  - rename:
      when:
        has_fields: ["forwarded.domain"]
      fields:
        - from: "forwarded.domain"
          to: "event.domain"
  - rename:
      when:
        has_fields: ["forwarded.data"]
      fields:
        - from: "forwarded.data"
          to: "destination.ip"

  - dissect:
      when:
        contains:
          message: "cached"
      tokenizer: "%{timestamp} %{+timestamp} %{+timestamp} %{service}[%{pid}]: %{action} %{domain} is %{data}"
      field: "message"
      target_prefix: "cached"
  - rename:
      when:
        has_fields: ["cached.action"]
      fields:
        - from: "cached.action"
          to: "event.action"
  - rename:
      when:
        has_fields: ["cached.domain"]
      fields:
        - from: "cached.domain"
          to: "event.domain"
  - rename:
      when:
        has_fields: ["cached.data"]
      fields:
        - from: "cached.data"
          to: "destination.ip"

  - dissect:
      when:
        contains:
          message: "gravity blocked"
      tokenizer: "%{timestamp} %{+timestamp} %{+timestamp} %{service}[%{pid}]: %{action} %{+action} %{domain} is %{ip}"
      field: "message"
      target_prefix: "blocked"
  - rename:
      when:
        has_fields: ["blocked.action"]
      fields:
        - from: "blocked.action"
          to: "event.action"
  - rename:
      when:
        has_fields: ["blocked.domain"]
      fields:
        - from: "blocked.domain"
          to: "event.domain"
  - rename:
      when:
        has_fields: ["blocked.ip"]
      fields:
        - from: "blocked.ip"
          to: "destination.ip"

  - dissect:
      when:
        contains:
          message: "regex blacklisted"
      tokenizer: "%{timestamp} %{+timestamp} %{+timestamp} %{service}[%{pid}]: %{action} %{+action} %{domain} is %{ip}"
      field: "message"
      target_prefix: "blacklisted"

  - dissect:
      when:
        contains:
          message: "exactly blacklisted"
      tokenizer: "%{timestamp} %{+timestamp} %{+timestamp} %{service}[%{pid}]: %{action} %{+action} %{domain} is %{ip}"
      field: "message"
      target_prefix: "blacklisted"
  - rename:
      when:
        has_fields: ["blacklisted.action"]
      fields:
        - from: "blacklisted.action"
          to: "event.action"
  - rename:
      when:
        has_fields: ["blacklisted.domain"]
      fields:
        - from: "blacklisted.domain"
          to: "event.domain"
  - rename:
      when:
        has_fields: ["blacklisted.ip"]
      fields:
        - from: "blacklisted.ip"
          to: "destination.ip"

output.elasticsearch:
  hosts: ["https://es01:9200"]

#  index: "logs-%{+yyyy.MM.dd}"
#  indices:
#    - index: "suricata-logs-%{+yyyy.MM.dd}"
#      when.equals:
#        event.module: "suricata"
#    - index: "audit-logs-%{+yyyy.MM.dd}"
#      when.equals:
#        event.module: "auditd"
#    - index: "system-logs-%{+yyyy.MM.dd}"
#      when.equals:
#        event.module: "system"
  username: elastic
  password: '${ELASTICSEARCH_PASSWORD}'
  ssl:
    certificate_authorities: "/usr/share/elasticsearch/config/certs/ca/ca.crt"
    certificate: "/usr/share/elasticsearch/config/certs/filebeat/filebeat.crt"
    key: "/usr/share/elasticsearch/config/certs/filebeat/filebeat.key"