hostname: "ryzen9"
agent.hostname: "ryzen9"
name: "ryzen9"
tags: ["ryzen9", "suricata", "dns"]

filebeat.config.inputs:
  enabled: true
  reload.enabled: true
  reload.period: 10s
  env:
    - localnet.env
    - pianet.env

#============================= Filebeat modules ===============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: true

  # Period on which files under path should be checked for changes
  reload.period: 120s

filebeat.modules:
- module: auditd
  log:
    enabled: true
    var.paths: ["/var/log/audit/audit.log*"]
- module: system
  syslog:
    enabled: true
    var.paths: ["/var/log/syslog*"]
  auth:
    enabled: true
    var.paths: ["/var/log/auth.log*"]

# ======================= Elasticsearch template setting =======================

#setup.template.enabled: true
#setup.template.name: "filebeat-%{[agent.version]}"
#setup.template.pattern: "filebeat-%{[agent.version]}-*"

setup.template.settings:
  index.number_of_shards: 3
  index.number_of_replicas: 1
  #index.codec: best_compression
  #_source.enabled: false

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

###
### Local Networks
###

  - add_fields:
      when:
        or:
          - contains:
              source.ip: "10.1.1."
          - contains:
              source.ip: "10.10.10."
          - contains:
              source.ip: "192.168.1."
      target: 'source.geo'
      fields:
        location: POINT (${localnet_geo_LON} ${localnet_geo_LAT})
        country_name: '${localnet_geo_COUNTRY}'
        country_iso_code: '${localnet_geo_COUNTRYCODE}'
        region_iso_code: '${localnet_geo_REGION}'
        continent_name: '${localnet_geo_TIMEZONE}'
        region_name: '${localnet_geo_REGIONNAME}'
        city_name: '${localnet_geo_CITY}'

  - add_fields:
      when:
        or:
          - contains:
              source.ip: "10.1.1."
          - contains:
              source.ip: "10.10.10."
          - contains:
              source.ip: "192.168.1."
      target: 'source.as'
      fields:
        organization.name: '${localnet_geo_ORG}'

  - add_fields:
      when:
        or:
          - contains:
              destination.ip: "10.1.1."
          - contains:
              destination.ip: "10.10.10."
          - contains:
              destination.ip: "192.168.1."
      target: 'destination.geo'
      fields:
        location: POINT (${localnet_geo_LON} ${localnet_geo_LAT})
        country_name: '${localnet_geo_COUNTRY}'
        country_iso_code: '${localnet_geo_COUNTRYCODE}'
        region_iso_code: '${localnet_geo_REGION}'
        continent_name: '${localnet_geo_TIMEZONE}'
        region_name: '${localnet_geo_REGIONNAME}'
        city_name: '${localnet_geo_CITY}'

  - add_fields:
      when:
        or:
          - contains:
              destination.ip: "10.1.1."
          - contains:
              destination.ip: "10.10.10."
          - contains:
              host.mac: "192.168.1."
      target: 'destination.as'
      fields:
        organization.name: '${localnet_geo_ORG}'

###
### WireGuard
###

  - add_fields:
      when:
        or:
          - contains:
              source.ip: '${pianet_iface_WG0}'
      target: 'source.geo'
      fields:
        location: POINT (${pianet_geo_LON} ${pianet_geo_LAT})
        country_name: '${pianet_geo_COUNTRY}'
        country_iso_code: '${pianet_geo_COUNTRYCODE}'
        region_iso_code: '${pianet_geo_REGION}'
        continent_name: '${pianet_geo_TIMEZONE}'
        region_name: '${pianet_geo_REGIONNAME}'
        city_name: '${pianet_geo_CITY}'

  - add_fields:
      when:
        or:
          - contains:
              source.ip: '${pianet_iface_WG0}'
      target: 'source.as'
      fields:
        organization.name: '${pianet_geo_ORG}'

  - add_fields:
      when:
        or:
          - contains:
              destination.ip: '${pianet_iface_WG0}'
      target: 'destination.geo'
      fields:
        location: POINT (${pianet_geo_LON} ${pianet_geo_LAT})
        country_name: '${pianet_geo_COUNTRY}'
        country_iso_code: '${pianet_geo_COUNTRYCODE}'
        region_iso_code: '${pianet_geo_REGION}'
        continent_name: '${pianet_geo_TIMEZONE}'
        region_name: '${pianet_geo_REGIONNAME}'
        city_name: '${pianet_geo_CITY}'

  - add_fields:
      when:
        or:
          - contains:
              destination.ip: '${pianet_iface_WG0}'
      target: 'destination.as'
      fields:
        organization.name: '${pianet_geo_ORG}'

###
### DNS PIA UPSTREAM
###

  - add_fields:
      when:
        or:
          - contains:
              destination.ip: "10.0.0.241"
      target: 'destination.geo'
      fields:
        location: POINT (${pianet_geo_LON} ${pianet_geo_LAT})
        country_name: '${pianet_geo_COUNTRY}'
        country_iso_code: '${pianet_geo_COUNTRYCODE}'
        region_iso_code: '${pianet_geo_REGION}'
        continent_name: '${pianet_geo_TIMEZONE}'
        region_name: '${pianet_geo_REGIONNAME}'
        city_name: '${pianet_geo_CITY}'

  - add_fields:
      when:
        or:
          - contains:
              destination.ip: "10.0.0.241"
      target: 'destination.as'
      fields:
        organization.name: '${pianet_geo_ORG}'

output.elasticsearch:
  hosts: ["https://es01:9200"]

#  index: "logs-%{+yyyy.MM.dd}"
#  indices:
#    - index: "suricata-logs-%{+yyyy.MM.dd}"
#      when.equals:
#        event.module: "suricata"
#    - index: "audit-logs-%{+yyyy.MM.dd}"
#      when.equals:
#        event.module: "auditd"
#    - index: "system-logs-%{+yyyy.MM.dd}"
#      when.equals:
#        event.module: "system"
  username: elastic
  password: '${ELASTICSEARCH_PASSWORD}'
  ssl:
    certificate_authorities: "/usr/share/elasticsearch/config/certs/ca/ca.crt"
    certificate: "/usr/share/elasticsearch/config/certs/filebeat/filebeat.crt"
    key: "/usr/share/elasticsearch/config/certs/filebeat/filebeat.key"