filter {
  json {
    source => "message"
    target => "suricata"
  }

  http {
    url => "https://otx.alienvault.com/api/v1/indicators/IPv4/%{[suricata][dest_ip]}"
    verb => "GET"
    headers => {
      "X-OTX-API-KEY" => "4daa2a9e13deb6172bb8c79e6768ca3ebb6ed1b7bf986bb594e5e0287cfbad4a"
    }
    target_body => "[@metadata][otx]"
  }
}

output {
  elasticsearch {
    hosts => "https://127.0.0.1:9200"
    user => "${ELASTICSEARCH_USERNAME}"
    password => "${ELASTICSEARCH_PASSWORD}"
    index => "suricata-otx-%{+yyyy.MM.dd}"
    ssl_enabled => true
    ssl_certificate_authorities => "${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}"
  }
}